export interface sectionOneDataType {
  id: string,
  lightBg: boolean,
  lightText: boolean,
  lightTextDesc: boolean,
  topLine: string,
  headLine: string,
  description: string,
  buttonLabel: string,
  imgStart: boolean,
  img: string,
  alt: string,
  primary: boolean,
  darkText: boolean,
  dark?: boolean,
  dark2?: boolean,
}

export const sectionOneData = {
  id: 'page1',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Section one',
  headLine: 'This is Headline',
  description: "This is Description",
  buttonLabel: "Button name",
  imgStart: false,
  img: "img1",
  alt: 'section1',
  dark: false,
  primary: false,
  darkText: true,
}
export const sectionOneData2 = {
  id: 'page2',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Section two',
  headLine: 'This is Headline',
  description: "This is Description",
  buttonLabel: "Button name",
  imgStart: true,
  img: "img2",
  alt: 'section2',
  dark: true,
  primary: true,
  darkText: false,
}
export const sectionOneData3 = {
  id: 'page3',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Section three',
  headLine: 'This is Headline',
  description: "This is Description",
  buttonLabel: "Button name",
  imgStart: false,
  img: "img3",
  alt: 'section3',
  dark: false,
  primary: false,
  darkText: true,
}